
CREATE TABLE PROV_BUS_ENTTY
(
  PROV_KEY INT
, BUS_ENTTY_KEY INT
, EFF_DT DATE
, TERMNTN_DT DATE
, PROV_BUS_ENTTY_RELSHP_TY_CD VARCHAR(25)
, CRETD_TIMESTMP TIMESTAMP(6)
, CRETD_BY VARCHAR(18)
, LAST_UPDTD_BY VARCHAR(18)
, LAST_UPDTD_TIMESTMP TIMESTAMP(6)
, SRC_SYS_CRET_USR_ID VARCHAR(18)
, SRC_SYS_CRET_TIMESTMP TIMESTAMP(6) DEFAULT NULL
, SRC_SYS_LAST_UPDT_USR_ID VARCHAR(18)
, SRC_SYS_LAST_UPDT_TIMESTMP TIMESTAMP(6) DEFAULT NULL
, SRC_SYS_CD VARCHAR(10)
, DEL_TIMESTMP TIMESTAMP(6)
);
