CREATE TABLE PROV (
  PROV_KEY INT
, PROV_TY_CD VARCHAR(25)
, EFF_DT DATE
, TERMNTN_DT DATE
, PROV_UNDR_REVW_IND CHAR(1)
, ORGANZTN_NM VARCHAR(100)
, FRST_NM VARCHAR(100)
, LAST_NM VARCHAR(100)
, MID_NM VARCHAR(25)
, NM_SFX VARCHAR(20)
, SALUTN_NM VARCHAR(20)
, CPF_PROV_TY_CD CHAR(2)
, CRETD_BY VARCHAR(18)
, CRETD_TIMESTMP TIMESTAMP(6)
, LAST_UPDTD_BY VARCHAR(18)
, LAST_UPDTD_TIMESTMP TIMESTAMP(6)
, HCPM_PRACTNR_ID NUMBER(38, 0)
, HCPM_PROV_ID NUMBER(38, 0)
, STOP_USG_IND CHAR(1)
, STOP_USG_REASN_DESC VARCHAR(25)
, SRC_SYS_CRET_USR_ID VARCHAR(18)
, SRC_SYS_CRET_TIMESTMP TIMESTAMP(6) DEFAULT NULL
, SRC_SYS_LAST_UPDT_USR_ID VARCHAR(18)
, SRC_SYS_LAST_UPDT_TIMESTMP TIMESTAMP(6) DEFAULT NULL
, SRC_SYS_CD VARCHAR(10)
, BRTH_DT DATE
, GENDR_CD CHAR(1)
, ATYPICAL_PROV_IND CHAR(1)
, DEL_TIMESTMP TIMESTAMP(6)
, SSN CHAR(9)
, DOD_IND CHAR(1)
, CPF_PROV_ID CHAR(7)
);

CREATE SEQUENCE PROV_KEY_SEQUENCE START 1;