CREATE TABLE ABC (
  AFIELD VARCHAR(100)
, COLUMN1 INT
, COLUMN2 INT
, DATECOLUMN DATE
, TIMESTAMPCOLUMN TIMESTAMP
, LAST_UPDTD_TIMESTMP TIMESTAMP NULL
, LAST_UPDTD_BY CHAR NULL
, CRETD_TIMESTMP TIMESTAMP NULL
, CRETD_BY CHAR NULL
);
